### ISSUE TITLE
Cartopy installed but unable to import

### ISSUE THREAD

**Issue by gkb999** [nicrie/xeofs#38] opened 2023-06-08 23:57 UTC
Hi Niclas @nicrie,
I'm installing xeofs in a newer desktop. I'm working on xeofs since months now, and greatly appreciate the support.

To my surprise, I'm unable to import cartopy this time.
I tried creating a newer enviromnet and installing
```python
(xeof_c) C:\Users\buradagi>conda install -c conda-forge xeofs cartopy
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.10.3
  latest version: 23.5.0

Please update conda by running

    $ conda update -n base -c defaults conda



# All requested packages already installed.


(xeof_c) C:\Users\buradagi>conda activate xeofs

(xeofs) C:\Users\buradagi>conda install -c conda-forge xeofs cartopy
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.10.3
  latest version: 23.5.0

Please update conda by running

    $ conda update -n base -c defaults conda



# All requested packages already installed.
```
When I try to import:
![image](https://github.com/nicrie/xeofs/assets/7091088/bb8d7894-c8e5-4824-b1dc-418ee6075d3d)

What could be the issue?
I almost created 4 new environments now, and tried multiple ways.
Cartopy is installed but on Jupyter Notebook I'm unable to install.

**Comment by nicrie** [comment] 2023-06-19 09:50
Thank you for your kind words! :) And sorry for the late reply I took some weeks off.
As to the error message, I admit I am not an expert of anaconda. I guess you tried to install `xeofs` in a fresh environment and the installation looks fine to me. Just two ideas for narrowing down the issue a bit:

1. Are you sure the issue is related to `xeofs`? Did you try to install `cartopy` only and then to import it? If the error persist it would indicate rather a problem in your environment/cartopy than with `xeofs`.
2. Did you try updating your conda version as suggested? I am not sure but perhaps it helps?

**Comment by nicrie** [comment] 2023-08-06 10:43
Hey @gkb999 could you solve your problem in the meantime? If so I'd close this issue.

**Comment by gkb999** [comment] 2023-08-25 08:44
> Hey @gkb999 could you solve your problem in the meantime? If so I'd close this issue.

Sorry, I could see it later. It is working perfectly.
Had some internal system not issues, not the package one

**Closed** 2023-08-26 23:27 UTC
